"""Convert a pinned eval notebook into a batch script for HPC reruns.

The notebook's own code is kept verbatim so a rerun executes the same driver that
produced the paper numbers. Three things are injected:
  1. after the ``CFG = ExpConfig()`` cell: overrides loaded from $VERIFY_OVERRIDES (JSON);
  2. before the ``# Build models`` cell: optional ``use_cross_attn`` ablation default;
  3. at the end: the per-epoch ``history`` and final wandb summary are dumped to $VERIFY_OUT.
Cells after the training cell (plots, mechanism visuals) are dropped.

Usage: python nb2py.py NOTEBOOK.ipynb OUT.py
"""
import json
import sys

OVERRIDES = '''
# --- injected by nb2py: apply per-run overrides ---
import json as _vjson, os as _vos
_VERIFY_OVR = _vjson.load(open(_vos.environ["VERIFY_OVERRIDES"]))
for _k, _v in _VERIFY_OVR.items():
    if isinstance(_v, list):
        _v = tuple(_v)
    setattr(CFG, _k, _v)
print("VERIFY overrides applied:", _VERIFY_OVR)
print(CFG)
'''

XATTN = '''
# --- injected by nb2py: cross-attention ablation (default keeps original behaviour) ---
import functools as _vft
if not bool(getattr(CFG, "use_cross_attn", True)):
    _orig_init = logic_llama_mod.LogicLlamaModel.__init__
    @_vft.wraps(_orig_init)
    def _no_xattn_init(self, *a, **kw):
        kw["use_cross_attn"] = False
        _orig_init(self, *a, **kw)
    logic_llama_mod.LogicLlamaModel.__init__ = _no_xattn_init
    print("VERIFY: use_cross_attn=False patched into LogicLlamaModel")
'''

DUMP = '''
# --- injected by nb2py: persist results ---
import json as _vjson, os as _vos, math as _vmath
def _vclean(x):
    if isinstance(x, float) and not _vmath.isfinite(x):
        return None
    if isinstance(x, dict):
        return {k: _vclean(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [_vclean(v) for v in x]
    try:
        _vjson.dumps(x)
        return x
    except TypeError:
        return str(x)
_vsum = {}
try:
    _vsum = dict(run.summary._as_dict()) if hasattr(run.summary, "_as_dict") else {}
except Exception as _e:
    _vsum = {"_summary_error": str(_e)}
_vout = {"history": _vclean(history), "param_count": param_count, "summary": _vclean(_vsum),
         "overrides": _VERIFY_OVR, "wandb_run_id": getattr(run, "id", None)}
_vos.makedirs(_vos.path.dirname(_vos.environ["VERIFY_OUT"]), exist_ok=True)
with open(_vos.environ["VERIFY_OUT"], "w") as _f:
    _vjson.dump(_vout, _f, indent=1)
print("VERIFY results written to", _vos.environ["VERIFY_OUT"])
'''


def main(nb_path: str, out_path: str) -> None:
    cells = ["".join(c["source"]) for c in json.load(open(nb_path, encoding="utf-8"))["cells"]
             if c["cell_type"] == "code"]
    parts = []
    seen_cfg = seen_build = seen_train = False
    for src in cells:
        if src.lstrip().startswith("# Build models"):
            parts.append(XATTN)
            seen_build = True
        parts.append(src)
        if "CFG = ExpConfig()" in src:
            parts.append(OVERRIDES)
            seen_cfg = True
        if "K_EPOCHS = CFG.k_epochs" in src:
            seen_train = True
            break
    if not (seen_cfg and seen_build and seen_train):
        raise SystemExit(f"{nb_path}: injection anchors missing cfg={seen_cfg} build={seen_build} train={seen_train}")
    parts.append(DUMP)
    header = f"# AUTO-GENERATED by nb2py.py from {nb_path}; do not edit.\n"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header + "\n\n".join(parts) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
